import { type LoanedGame } from "@/app/lib/types/loaned-game"

export const loanedGameData: LoanedGame[] = [
  {
    loanId: "1",
    borrower: "Antonio Goodman",
    borrowerId: "3",
    owner: "Krishan Duran",
    ownerId: "2",
    loanedDate: "2025-01-01",
    title: "Space Base",
    shelf: "Owned",
    playingTime: 60,
    playerCount: "2-5",
    age: "14+",
    thumbnail:
      "https://cf.geekdo-images.com/MHhQxXVjiaa6C-04nGiIWw__thumb/img/rgETRyeuYs_wiZ5y-9Zj5H8kyFo=/fit-in/200x150/filters:strip_icc()/pic6640638.jpg",
    isPrivate: false,
    isLoaned: true,
    isExpansion: false,
    image: null,
    game: {
      age: null,
      bgg_id: null,
      created_at: "",
      id: "",
      image: null,
      is_expansion: false,
      max_players: null,
      min_players: null,
      playing_time: null,
      publisher: null,
      thumbnail: null,
      title: null,
      year_published: null,
    },
    created_at: "",
    game_id: "",
    id: 0,
    is_loaned: false,
    is_private: false,
    modified_at: "",
    user_id: "",
  },
  {
    loanId: "2",
    borrower: "Caitlin Weaver",
    borrowerId: "1",
    owner: "Krishan Duran",
    ownerId: "2",
    loanedDate: "2024-08-25",
    title: "Gloomhaven",
    shelf: "Not Interested",
    playingTime: 120,
    playerCount: "1-4",
    age: "12+",
    thumbnail:
      "https://cf.geekdo-images.com/sZYp_3BTDGjh2unaZfZmuA__thumb/img/veqFeP4d_3zNhFc3GNBkV95rBEQ=/fit-in/200x150/filters:strip_icc()/pic2437871.jpg",
    isPrivate: false,
    isLoaned: true,
    isExpansion: false,
    image: null,
    game: {
      age: null,
      bgg_id: null,
      created_at: "",
      id: "",
      image: null,
      is_expansion: false,
      max_players: null,
      min_players: null,
      playing_time: null,
      publisher: null,
      thumbnail: null,
      title: null,
      year_published: null,
    },
    created_at: "",
    game_id: "",
    id: 0,
    is_loaned: false,
    is_private: false,
    modified_at: "",
    user_id: "",
  },
  {
    loanId: "3",
    borrower: "Krishan Duran",
    borrowerId: "2",
    owner: "Caitlin Weaver",
    ownerId: "1",
    loanedDate: "2024-12-13",
    title: "Azul",
    shelf: null,
    playingTime: 30,
    playerCount: "2-4",
    age: "8+",
    thumbnail:
      "https://cf.geekdo-images.com/aPSHJO0d0XOpQR5X-wJonw__thumb/img/ccsXKrdGJw-YSClWwzVUwk5Nh9Y=/fit-in/200x150/filters:strip_icc()/pic6973671.png",
    isPrivate: false,
    isLoaned: true,
    isExpansion: false,
    image: null,
    game: {
      age: null,
      bgg_id: null,
      created_at: "",
      id: "",
      image: null,
      is_expansion: false,
      max_players: null,
      min_players: null,
      playing_time: null,
      publisher: null,
      thumbnail: null,
      title: null,
      year_published: null,
    },
    created_at: "",
    game_id: "",
    id: 0,
    is_loaned: false,
    is_private: false,
    modified_at: "",
    user_id: "",
  },
  {
    loanId: "4",
    borrower: "Antonio Goodman",
    borrowerId: "3",
    owner: "Caitlin Weaver",
    ownerId: "1",
    loanedDate: "2025-01-29",
    title: "Scythe",
    shelf: "Want",
    playingTime: 90,
    playerCount: "1-5",
    age: "14+",
    thumbnail:
      "https://cf.geekdo-images.com/7k_nOxpO9OGIjhLq2BUZdA__thumb/img/eQ69OEDdjYjfKg6q5Navee87skU=/fit-in/200x150/filters:strip_icc()/pic3163924.jpg",
    isPrivate: false,
    isLoaned: true,
    isExpansion: false,
    image: null,
    game: {
      age: null,
      bgg_id: null,
      created_at: "",
      id: "",
      image: null,
      is_expansion: false,
      max_players: null,
      min_players: null,
      playing_time: null,
      publisher: null,
      thumbnail: null,
      title: null,
      year_published: null,
    },
    created_at: "",
    game_id: "",
    id: 0,
    is_loaned: false,
    is_private: false,
    modified_at: "",
    user_id: "",
  },
]
